spring.application.name: inventory-summary-1
server.port: 9001

spring.cloud.stream.bindings:
  input:
    destination: bohUpdate
    consumer:
      useNativeDecoding: true
  output:
    destination: bohSummary
    producer:
      useNativeEncoding: true

spring.cloud.stream.kafka.streams:
  binder:
    configuration:
      default.key.serde: org.apache.kafka.common.serialization.Serdes$IntegerSerde
      default.value.serde: org.apache.kafka.common.serialization.Serdes$BytesSerde
      commit.interval.ms: 1000
      schema.registry.url: http://localhost:8081
  bindings:
    input.consumer.valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
    output.producer.valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
# Only for running the sample producer
#
spring.cloud.stream.bindings.producer-output:
  destination: bohUpdate
  producer:
    useNativeEncoding: true
spring.cloud.stream.kafka.binder.configuration:
  schema.registry.url: http://localhost:8081
  key.serializer: org.apache.kafka.common.serialization.IntegerSerializer
  value.serializer: com.example.streamtableupdate.CustomAvroSerializer
spring.cloud.stream.kafka.bindings.producer-output.producer.messageKeyExpression: headers['update-event-id']
